# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn package
        ls -al
        ls -al target/
        mvn package
        ls -al
        ls -al target/
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: IniciumBot
        path: target/Inicium-*.jar
  deploy:
    runs-on: [self-hosted, raspberrypi]
    needs: build
    steps:
    - name: Cleanup destination folder
      continue-on-error: true
      run: rm ./*.jar
    - name: Download JAR
      uses: actions/download-artifact@v4
      with:
        name: IniciumBot
        path: ./
    - name: Deploy JAR
      run: |
        mv ./Inicium-*.jar /home/inicium/IniciumBot/IniciumBot.jar
        sudo systemctl restart iniciumbot.service
